@baseUrl = http://localhost:3333
@authToken={{authenticate.response.body.access_token}}
# @name create_account
POST {{baseUrl}}/accounts
Content-type: application/json

{
  "name": "John Doe",
  "email": "jhondoe3@email.com",
  "password": "123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-type: application/json

{
  "email": "pazzim@email.com",
  "password": "123456"
}

###

# @name get_user
GET {{baseUrl}}/user/me
Content-type: application/json
Authorization: Bearer {{authToken}}
